import type { DashboardSession, SettingsInfo, TimelineItem } from '../features/sessions/types';

export const mockSessions: DashboardSession[] = [
  {
    id: 'mock-session-1',
    cwd: '/Users/albert/projects/api',
    repoRoot: '/Users/albert/projects/api',
    repoName: 'api',
    branch: 'feat/codex-control',
    model: 'gpt-5.4',
    transcriptPath: '/tmp/mock-session-1.jsonl',
    status: 'working',
    lastPrompt: 'Audit the webhook pipeline and summarize the next fix.',
    lastCommand: 'cargo test --workspace',
    lastAssistantMessage: 'Current failures are isolated to hook normalization.',
    startedAt: '2026-04-23T18:00:00Z',
    updatedAt: '2026-04-23T18:21:00Z',
    approvalState: 'not_required',
    changedFilesCount: 4,
    stagedCount: 1,
    unstagedCount: 3,
    diffStat: '4 files changed, 128 insertions(+), 22 deletions(-)',
    transcriptPreview: 'User: Audit the webhook pipeline\nAssistant: Current failures are isolated to hook normalization.',
    process: {
      pid: 1144,
      parentPid: 998,
      cwd: '/Users/albert/projects/api',
      command: 'codex --model gpt-5.4',
      uptimeSeconds: 1840,
    },
    source: 'mock',
    isStale: false,
  },
  {
    id: 'mock-session-2',
    cwd: '/Users/albert/projects/web',
    repoRoot: '/Users/albert/projects/web',
    repoName: 'web',
    branch: 'main',
    model: 'gpt-5.4-mini',
    transcriptPath: null,
    status: 'waiting_approval',
    lastPrompt: 'Open the staging logs and inspect the last deploy error.',
    lastCommand: 'rm -rf dist',
    lastAssistantMessage: null,
    startedAt: '2026-04-23T16:10:00Z',
    updatedAt: '2026-04-23T18:18:00Z',
    approvalState: 'blocked_by_policy',
    changedFilesCount: 9,
    stagedCount: 0,
    unstagedCount: 9,
    diffStat: '9 files changed, 214 insertions(+), 17 deletions(-)',
    transcriptPreview: null,
    process: {
      pid: 2280,
      parentPid: 1201,
      cwd: '/Users/albert/projects/web',
      command: 'codex resume mock-session-2',
      uptimeSeconds: 5200,
    },
    source: 'mock',
    isStale: false,
  },
];

export const mockTimeline: TimelineItem[] = [
  {
    id: 'evt-1',
    sessionId: 'mock-session-1',
    eventName: 'UserPromptSubmit',
    createdAt: '2026-04-23T18:10:00Z',
    command: null,
    approvalRequest: null,
    resultSummary: null,
    transcriptPath: '/tmp/mock-session-1.jsonl',
    gitState: '4 files changed',
    payload: { prompt: 'Audit the webhook pipeline and summarize the next fix.' },
  },
  {
    id: 'evt-2',
    sessionId: 'mock-session-1',
    eventName: 'PreToolUse',
    createdAt: '2026-04-23T18:12:00Z',
    command: 'cargo test --workspace',
    approvalRequest: null,
    resultSummary: null,
    transcriptPath: '/tmp/mock-session-1.jsonl',
    gitState: 'unstaged: 3',
    payload: { tool_name: 'Bash' },
  },
  {
    id: 'evt-3',
    sessionId: 'mock-session-1',
    eventName: 'PostToolUse',
    createdAt: '2026-04-23T18:15:00Z',
    command: 'cargo test --workspace',
    approvalRequest: null,
    resultSummary: '1 failing test in hook normalization',
    transcriptPath: '/tmp/mock-session-1.jsonl',
    gitState: 'branch: feat/codex-control',
    payload: { exit_code: 101 },
  },
];

export const mockSettings: SettingsInfo = {
  paths: {
    dataDir: '/tmp/codex-control',
    databasePath: '/tmp/codex-control/codex-control.db',
    spoolPath: '/tmp/codex-control/spool/events.jsonl',
  },
  hookCliAvailable: false,
  hookCliPath: null,
  storeMode: 'mock',
  lastIngestAt: null,
  hookInstallSnippet: 'cargo install --path packages/hook-cli',
  notes: ['Development fallback active. Mock data is shown because the desktop backend is not connected.'],
};
